import "../../globals.css"


import { Inter as FontSans, Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";
import { ReactNode } from "react";
import {} from "next-auth";
import { Metadata } from "next/types";
import { auth } from "@/auth";
import SessionProvider from "@/components/auth/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import { redirect } from "next/navigation";
import { Poppins, Gowun_Batang } from "next/font/google";
const gowun_batang = Gowun_Batang({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-serifFont",
});
const poppins = Poppins({
  subsets: ["latin-ext"],
  weight: ["400", "100", "200", "300", "500", "600", "700"],
  variable: "--font-sansFont",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
type Props = {
  children: ReactNode;
};
export default async function RootLayout({ children }: Props) {
  const session = await auth();
  if(session) redirect("/")
  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={cn("min-h-screen bg-background font-sans antialiased", poppins.variable,gowun_batang.variable)}>
              <div className="sm:pl-14">{children}</div>
              <Toaster />
        </body>
      </html>
    </SessionProvider>
  );
}
